name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      log_error_file:
        description: "Create log file if there is any errors"
        required: false
        type: boolean
        default: false


jobs:
  login_and_test:
    runs-on: ubuntu-latest
    steps:
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_EMMA_USERNAME }}
        password: ${{ secrets.DOCKER_EMMA_PASSWORD }}
        
    - uses: actions/checkout@v4

    - name: Set up Python environment
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run tests with pytest
      env:
        API_KEY: ${{ secrets.API_KEY }}
      run: python -m pytest

    - name: Create error log if log_error_file is true
      if: ${{ failure() && github.event.inputs.log_error_file == 'true' }}
      uses: actions/upload-artifact@v3
      with:
        name: Create log file
        path: error_logs/test_error_log.txt
    
  build_app: 
    runs-on: ubuntu-latest
    needs: login_and_test
    if: ${{ success() }}
    steps: 
      - name: Build the Docker image
        run: docker build --build-arg API_KEY=${{ secrets.API_KEY }} -t ${{ secrets.DOCKER_EMMA_USERNAME }}/devops:latest --file Dockerfile .

      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_EMMA_USERNAME }}/devops:latest
